# Generated by Django 3.2.13 on 2024-05-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('temperature_sensitivity', models.CharField(choices=[('cold', 'I feel cold easily'), ('neutral', 'I am okay with most temperatures'), ('hot', 'I feel hot easily')], max_length=10)),
                ('clothing_style', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sporty', 'Sporty')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('suitable_for', models.CharField(max_length=50)),
                ('recommended_for', models.ManyToManyField(related_name='recommendations', to='core.UserProfile')),
            ],
        ),
    ]
